check

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -38,7 +38,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: test
     steps:
-      - name: Checkout the repo 
+      - name: Checkout the repo
         uses: actions/checkout@v4
 
       - name: Build container image
@@ -54,12 +54,15 @@ jobs:
 
       - name: Remove old image tags from registry
         run: |
-          # Get the list of image tags
-          IMAGE_TAGS=$(doctl registry repository list-tags $IMAGE_NAME | awk '{print $1}')
-          # Remove all old tags except for the latest one
+          echo "Fetching tags for image $IMAGE_NAME"
+          # Получаем список всех тегов для образа, исключая текущий тег
+          IMAGE_TAGS=$(doctl registry repository list-tags $IMAGE_NAME --format "name" --no-header)
+          
           for TAG in $IMAGE_TAGS; do
             if [ "$TAG" != "${GITHUB_SHA:0:7}" ]; then
-              doctl registry repository delete-manifest $IMAGE_NAME $TAG --force
+              echo "Deleting old tag: $TAG"
+              # Удаляем старый тег (манифест), если он не текущий
+              doctl registry repository delete-manifest $IMAGE_NAME $TAG --force || echo "Failed to delete $TAG"
             fi
           done
 
@@ -71,7 +74,7 @@ jobs:
     needs: build_and_push
 
     steps:
-      - name: Deploy to Digital Ocean droplet via SSH action
+      - name: Deploy to DigitalOcean droplet via SSH action
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
@@ -79,13 +82,19 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           envs: IMAGE_NAME,REGISTRY,LOGS_PATH,IMAGE_PATH,DIGITALOCEAN_ACCESS_TOKEN,GITHUB_SHA
           script: |
-            # Login to registry
+            # Логинимся в реестр
             docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
-            # Stop running container if it exists
-            docker stop $IMAGE_NAME || true
-            # Remove the old container
-            docker rm $IMAGE_NAME || true
-            # Run a new container from the newly pushed image
+            
+            # Останавливаем старый контейнер, если он запущен
+            echo "Stopping container $IMAGE_NAME"
+            docker stop $IMAGE_NAME || echo "Container $IMAGE_NAME not running."
+
+            # Удаляем старый контейнер
+            echo "Removing container $IMAGE_NAME"
+            docker rm $IMAGE_NAME || echo "Container $IMAGE_NAME does not exist."
+
+            # Запускаем новый контейнер с последним образом
+            echo "Running new container $IMAGE_NAME"
             docker run -d \
               --restart always \
               --publish 8080:8080 \
